content = open("app/main.py", encoding="utf-8").read()
content = content.replace("from fastapi.staticfiles import StaticFiles\n", "")
content = content.replace('app.mount("/static", StaticFiles(directory="static"), name="static")\n', "")
open("app/main.py", "w", encoding="utf-8").write(content)
print("Done", len(content))
